In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
x = np.arange(1, 11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
x = np.zeros((3, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
x = np.random.randint(1, 11, size=(5, 5))
print(x)

[[ 5  3 10  9  3]
 [ 3  4  6  9 10]
 [ 2  7  7  7  2]
 [ 6  1  1  6  7]
 [10  1 10  9  3]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
x = np.random.rand(4, 4)
print(x)

[[0.16447416 0.47199978 0.56425677 0.25644609]
 [0.75201568 0.63096119 0.76231839 0.20489919]
 [0.98789565 0.42799164 0.87030478 0.16226784]
 [0.40859731 0.73353579 0.60617638 0.9670662 ]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
x = np.random.randint(1, 11, size=5)
y = np.random.randint(1, 11, size=5)
print(x + y)
print(x - y)
print(x * y)

[ 9 12 15 12  5]
[ 3 -2  5  0  3]
[18 35 50 36  4]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
x = np.random.randint(1, 11, size=7)
y = np.random.randint(1, 11, size=7)
print(np.dot(x, y))

143


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 3))
print(np.dot(x, y))

[[65 78 99]
 [47 53 81]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
x = np.random.randint(1, 11, size=(3, 3))
print(np.linalg.inv(x))

[[ 0.42105263  0.57894737 -0.89473684]
 [-0.36842105  0.36842105  0.15789474]
 [-0.21052632 -0.78947368  0.94736842]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
x = np.random.rand(4, 4)
print(x.T)

[[0.03289512 0.04955623 0.31522021 0.12645381]
 [0.45319716 0.1276534  0.64524562 0.05361448]
 [0.69874925 0.68262708 0.58641294 0.07111894]
 [0.62273969 0.03729567 0.04286636 0.27676312]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
x = np.random.randint(1, 11, size=(3, 4))
y = np.random.randint(1, 11, size=4)
print(np.dot(x, y))

[135  95  52]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
x = np.random.rand(2, 3)
y = np.random.rand(3)
print(np.dot(x, y))

[0.2487115  0.39664003]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print(x * y)

[[ 5 32]
 [36 30]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print(np.dot(x, y))

[[140  99]
 [109  77]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
x = np.random.randint(1, 101, size=(5, 5))
print(x.sum())               

1299


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
x = np.random.randint(1, 11, size=(4, 4))
y = np.random.randint(1, 11, size=(4, 4))
print(x - y)

[[-5 -3 -4  1]
 [ 6 -2  7 -4]
 [-2  6  0  1]
 [ 5 -1  6  3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
x = np.random.rand(3, 3)
print(x.sum(axis=0).reshape(-1, 1))

[[1.5949777 ]
 [1.52850109]
 [1.29457716]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
x = np.random.randint(1, 11, size=(3, 4))
print(np.square(x))

[[ 49  81   1  49]
 [  9 100  49  81]
 [ 16  16  49   9]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
x = np.random.randint(1, 51, size=4)
print(np.sqrt(x))

[4.35889894 3.87298335 4.         1.41421356]
