1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np

x = np.arange(1, 11)

print(x)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [2]:
x = np.zeros((3, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [3]:
x = np.random.randint(1, 11, size=(5, 5))
print(x)

[[ 4  1  1  5  1]
 [ 3  1  4  9  8]
 [ 2  3  7 10  2]
 [ 4 10  3  2  6]
 [ 7  6  3  5  2]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
x = np.random.rand(4, 4)
print(x)

[[0.78806215 0.39997334 0.615874   0.40727873]
 [0.27128522 0.20636983 0.57782154 0.74264107]
 [0.12000154 0.06880519 0.93872725 0.79948841]
 [0.56274168 0.73919186 0.34510034 0.81787828]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [5]:
x = np.random.randint(1, 11, size=5)
y = np.random.randint(1, 11, size=5)
print(x + y)
print(x - y)
print(x * y)

[10 11  8 12 16]
[ 4 -9  6  0  4]
[21 10  7 36 60]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [6]:
x = np.random.randint(1, 11, size=7)
y = np.random.randint(1, 11, size=7)
print(np.dot(x, y))

187


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [7]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 3))
print(np.dot(x, y))

[[33 73 33]
 [75 17 12]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [8]:
x = np.random.randint(1, 11, size=(3, 3))
print(np.linalg.inv(x))

[[ 0.69230769 -1.30769231  0.76923077]
 [-0.34615385  1.15384615 -0.88461538]
 [-0.15384615 -0.15384615  0.38461538]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [9]:
x = np.random.rand(4, 4)
print(x.T)

[[0.54514438 0.59759264 0.10478796 0.06838988]
 [0.73847568 0.52817726 0.51745457 0.61159637]
 [0.86760582 0.57947247 0.77299456 0.08135624]
 [0.09854444 0.56380447 0.91642509 0.55528596]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [10]:
x = np.random.randint(1, 11, size=(3, 4))
y = np.random.randint(1, 11, size=4)
print(np.dot(x, y))

[153 100 107]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [11]:
x = np.random.rand(2, 3)
y = np.random.rand(3)
print(np.dot(x, y))

[1.31170116 1.33861021]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [12]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print(x * y)

[[56 24]
 [ 7 60]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [13]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print(np.dot(x, y))

[[ 26 126]
 [  9  63]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [14]:
x = np.random.randint(1, 101, size=(5, 5))
print(x.sum())               

1329


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [15]:
x = np.random.randint(1, 11, size=(4, 4))
y = np.random.randint(1, 11, size=(4, 4))
print(x - y)

[[ 3 -1 -2 -2]
 [ 1  7  3  5]
 [-6 -4 -6 -8]
 [-6 -3  0  2]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [16]:
x = np.random.rand(3, 3)
print(x.sum(axis=0).reshape(-1, 1))

[[1.18320158]
 [1.95860484]
 [0.96588641]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [17]:
x = np.random.randint(1, 11, size=(3, 4))
print(np.square(x))

[[16  1  9  9]
 [36  9  4  1]
 [ 4 81 16  4]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [18]:
x = np.random.randint(1, 51, size=4)
print(np.sqrt(x))

[6.4807407  4.47213595 1.41421356 5.        ]
